### PR TITLE
OutTransfer transaction should not fail if transaction with id provided in property "transactionId" already exists in the database - Closes 1219

### LINKED ISSUE #1219: OutTransfer transaction should not fail if transaction with id provided in property "transactionId" already exists in the database
### Expected behavior
The OutTransfer transactions in the testnet should be processable.
### Actual behavior
The OutTransfer transaction with id: 7297225435992500205 fails on verification with the error: 
```
[{"id":"7297225435992500205","status":0,"errors":[{"jse_shortmsg":"Transaction 13227044664082109069 is already processed.","jse_info":{},"message":"Transaction 13227044664082109069 is already processed.","name":"TransactionError","id":"7297225435992500205","dataPath":""}]}]
```
### Steps to reproduce
Sync with testnet
### Which version(s) does this affect? (Environment, OS, etc...)
release/2.1.0

### PR DESCRIPTION
**Pull request by SargeKhan**
### What was the problem?
The OutTransfer transaction failed when asset.outTransfer.transactionId provided already existed in the database
### How did I fix it?
Removed the verification of transaction id provided in the asset field.
### How to test it?
Run the tests
### Review checklist

* The PR resolves #1219
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-transactions/src/7_out_transfer_transaction.ts [hunk 1]
```diff
@@ -192,22 +192,6 @@ export class OutTransferTransaction extends BaseTransaction {
 			);
 		}
 
-		const transactionExists = store.transaction.find(
-			(transaction: TransactionJSON) =>
-				transaction.id === this.asset.outTransfer.transactionId,
-		);
-
-		if (transactionExists) {
```
Comment (shuse2) [inline packages/lisk-transactions/src/7_out_transfer_transaction.ts:200]: maybe it was `!transactionExists`?

Comment (SargeKhan) [reply packages/lisk-transactions/src/7_out_transfer_transaction.ts:200]: No, I checked the implementation for outTransfer transaction in lisk-core. The check for outTransfer.transactionId was only used for verifying that multiple unconfirmed transactions with same outTransfer.transactionId do not get processed in the same block. (Doesn't make so much, but that's what i get from the implementation).

**Review by shuse2 — APPROVED** [review]
