### PR TITLE
Fix validation of asset data - Closes #1214

### LINKED ISSUE #1214: Transaction validate incorrectly throws error from assetToBytes
### Expected behavior

`validate` method for each transaction type should return a `TransactionResponse` with errors array instead of throwing.

### Actual behavior

When asset includes invalid data, `validate` --> `getBasicBytes` --> `assetToBytes` throws an error. 

### Steps to reproduce
```
const invalidTx = { "type": 0, "asset": { "data": { } }, ... };
const transferTx = new TransferTransaction(invalidTx);
transferTx.validate()
```

### PR DESCRIPTION
**Pull request by mitsuaki-u**
### What was the problem?

1. `assetToBytes` and `getBasicBytes` called after schema checks failed causing error.

2. `assetToJSON` was destructuring invalid assets in initialization stage, causing errors.

3. `.dataPath` in errors were missing when asset themselves were of invalid type

4. Validation process for dapp and vote transactions were throwing error 

### How did I fix it?

Early return if errors produced from schema and asset validation. 

`assetToJSON` now simply returns itself.

New function specifically for filling missing `.dataPath` in errors.

Fixed initialization and validation issues for dapp and vote transactions. 

### How to test it?

npm run rest

### Review checklist

* The PR resolves #1214 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-transactions/src/errors.ts [hunk 1]
```diff
@@ -87,9 +87,9 @@ export const convertToTransactionError = (
 	return errors.map(
 		error =>
 			new TransactionError(
-				`'${error.dataPath}' ${error.message}`,
+				`'${error.dataPath || '.asset'}' ${error.message}`,
```
Comment (shuse2) [inline packages/lisk-transactions/src/errors.ts:108]: At this point, I think non existent `dataPath` doesn't necessarily mean `.asset`

**Review by shuse2 — DISMISSED** [review]

File: packages/lisk-transactions/src/5_dapp_transaction.ts [hunk 2]
```diff
@@ -260,6 +261,11 @@ export class DappTransaction extends BaseTransaction {
 			);
 		}
 		const validLinkSuffix = ['.zip'];
+
+		if (errors.length > 0) {
```
Comment (shuse2) [inline packages/lisk-transactions/src/5_dapp_transaction.ts:263]: why return here?

File: packages/lisk-transactions/src/base_transaction.ts [hunk 3]
```diff
@@ -233,10 +233,20 @@ export abstract class BaseTransaction {
 	}
 
 	public validate(): TransactionResponse {
-		const errors = [...this._validateSchema(), ...this.validateAsset()];
+		const validateAssetErrors = this.validateAsset();
+		if (validateAssetErrors.length > 0) {
+			return createResponse(this.id, validateAssetErrors);
+		}
+
+		const validateSchemaErrors = this._validateSchema();
```
Comment (shuse2) [inline packages/lisk-transactions/src/base_transaction.ts]: i thought we are not going to split this? what is the purpose of separating this?
I think it's more useful to know all the invalid field (ie: base schema and asset schema validation result together)

**Review by shuse2 — DISMISSED** [review]

File: packages/lisk-transactions/src/base_transaction.ts (hunk 3 above)
Comment (mitsuaki-u) [reply packages/lisk-transactions/src/base_transaction.ts]: `_validateSchema` calls `toJSON` which in turn calls `assetToJSON`.  If validation of `asset` fails, calling `assetToJSON` throws an error. Therefore we separate here.

File: packages/lisk-transactions/src/5_dapp_transaction.ts (hunk 2 above)
Comment (mitsuaki-u) [reply packages/lisk-transactions/src/5_dapp_transaction.ts:263]: If asset does not pass validation we should not check fields like `this.asset.dapp.link` below, otherwise it will throw an error.

**Review by shuse2 — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
