### PR TITLE
Fix timestamp validation - Closes #1179

### LINKED ISSUE #1179: Negative timestamp should be allowed in transaction
### Expected behavior
Currently protocol allows negative timestamp

### Actual behavior
timestamp has to be positive integer

### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0-alpha.2-

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
Current protocol allows negative timestamp within int32

### How did I fix it?
Update the schema to allow negative number

### How to test it?
validate transaction with negative timestamp

### Review checklist

* The PR resolves #1179
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-transactions/src/utils/validation/schema.ts [hunk 1]
```diff
@@ -103,7 +103,7 @@ export const baseTransaction = {
 		},
 		timestamp: {
 			type: 'integer',
-			minimum: 0,
+			minimum: -2147483648,
```
Comment (SargeKhan) [inline packages/lisk-transactions/src/utils/validation/schema.ts:106]: Does it mean that we always accept transactions with negative timestamps or do we allow negative timestamps for a few transactions which are exceptions in the blockchain?

Comment (shuse2) [reply packages/lisk-transactions/src/utils/validation/schema.ts:106]: It seems like there is no exception and allowing negative number per current implementation.
https://github.com/LiskHQ/lisk/blob/development/framework/src/modules/http_api/schema/swagger.yml#L1278-L1283
https://github.com/LiskHQ/lisk/blob/development/framework/src/modules/chain/logic/transaction.js#L688-L696

**Review by SargeKhan — APPROVED** [review]

**Review by pablitovicente — APPROVED** [review]
