### PR TITLE
Fix to call super.verify - Closes #1033

### LINKED ISSUE #1033: Calling wrong function in custom transactions
### Expected behavior
In verify stage for transactions type `3,5,6,7`, it should call `super.verify`

### Actual behavior
It's calling `super.apply`

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
Verify was not calling the super.verify

### How did I fix it?
change apply to verify

### How to test it?
Add unit test

### Review checklist

* The PR resolves #1033 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-transactions/src/transactions/6_in_transfer_transaction.ts [hunk 1]
```diff
@@ -282,7 +282,7 @@ export class InTransferTransaction extends BaseTransaction {
 				new TransactionError(
 					`Account does not have enough LSK: ${
 						sender.address
-					}, balance: ${convertBeddowsToLSK(sender.balance)}.`,
+					},here?, balance: ${convertBeddowsToLSK(sender.balance)}.`,
```
Comment (SargeKhan) [inline packages/lisk-transactions/src/transactions/6_in_transfer_transaction.ts]: Typo?

**Review by SargeKhan — DISMISSED** [review]

File: packages/lisk-transactions/src/transactions/6_in_transfer_transaction.ts (hunk 1 above)
Comment (shuse2) [reply packages/lisk-transactions/src/transactions/6_in_transfer_transaction.ts]: ='( good catch

**Review by mitsuaki-u — APPROVED** [review]
