### PR TITLE
Check for network, version, protocol compatibility during handshake - Closes#1137

### LINKED ISSUE #1137: Check for network, version, protocol compatibility during handshake
### Expected behavior

We need to check network and protocol compatibility during the handshake in lisk-p2p.

### Actual behavior

Right now we don't have a check for network and protocol compatibility during the handshake.

### Steps to reproduce

N/A

### PR DESCRIPTION
**Pull request by ishantiw**
### Description

Add a field in P2P config to allow compatibility check functions to be inserted in the constructor. The checks will cover,

- Network compatibility (`nethash`)
- Version compatibility (`version`)
- Protocol version compatibility (`protocolVersion`)

### Review checklist

* The PR resolves #1137 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Review by 2snEM6 — DISMISSED** [review]

File: packages/lisk-p2p/src/p2p_types.ts [hunk 1]
```diff
@@ -113,6 +114,18 @@ export type P2PPeerSelectionForConnection = (
 	nodeInfo?: P2PNodeInfo,
 ) => ReadonlyArray<P2PDiscoveredPeerInfo>;
 
+export interface P2PPeerCheckCompatibility {
+	readonly networkCompatible?: P2PPeerNetworkCompatibility;
+	readonly protocolVersionCompatible?: P2PPeerProtocolVersionCompatibility;
+	readonly versionCompatible?: P2PPeerVersionCompatibility;
+}
+
+export type P2PPeerNetworkCompatibility = (nethash: string) => boolean;
```
Comment (shuse2) [inline packages/lisk-p2p/src/p2p_types.ts]: instead of specifying one by one, maybe
`P2PPeerNetworkCompatibility = (header: QueryObject) => boolean`
and i think we can provide the default by
checking nethash, version, and protocol version, and override them if it's provided?

File: packages/lisk-p2p/src/p2p.ts [hunk 2]
```diff
@@ -342,6 +350,76 @@ export class P2P extends EventEmitter {
 					return;
 				}
 
+				if (this._peerHandShakeChecks) {
+					if (this._peerHandShakeChecks.networkCompatible) {
```
Comment (shuse2) [inline packages/lisk-p2p/src/p2p.ts]: one `if` for both checking and executing should be fine?

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: packages/lisk-p2p/src/p2p_types.ts (hunk 1 above)
Comment (ishantiw) [reply packages/lisk-p2p/src/p2p_types.ts]: Although I have added this check now. But by default, all the nodes need to be compatible with each other in terms of minVersion, version and nethash which should be handled in module level in IMO. Now anyone using p2p library needs to pass these values. @jondubois What do you think?

Comment (jondubois) [reply packages/lisk-p2p/src/p2p_types.ts]: I think it would be simpler if there was a single compatibility function instead of three different ones. The compatibility function could either throw or return a custom error on failure which can be handled inside the P2P class; then the `error.message` from the function could be used as the disconnect reason; that way the user can make the error reason be anything; so it gives them more flexibility.

Also, I think that instead of `QueryObject`, we could go one step further and just pass `incomingPeerInfo` (`P2PDiscoveredPeerInfo`) to the function.

Comment (ishantiw) [reply packages/lisk-p2p/src/p2p_types.ts]: After the discussion with @jondubois, we decided to keep `networkCompatibility` and `protocolVersionCompatibility` checks so that we avoid peers from other networks to connect by default. Also, we are going to have one function for all the compatibility checks so that user is not confined to only these 3 checks but also could provide its own check.

File: packages/lisk-p2p/src/p2p.ts [hunk 3]
```diff
@@ -228,6 +231,10 @@ export class P2P extends EventEmitter {
 		this._discoveryInterval = config.discoveryInterval
 			? config.discoveryInterval
 			: DEFAULT_DISCOVERY_INTERVAL;
+
+		this._peerHandshakeChecks = config.peerhandShakeChecks
```
Comment (jondubois) [inline packages/lisk-p2p/src/p2p.ts]: Inconsistent capitalization: `peerhandShakeChecks` should be `peerHandshakeChecks`.

I prefer `peerHandshakeCheck` (singular) but this is minor.

**Review by jondubois — CHANGES_REQUESTED** [review]

**Review by jondubois — APPROVED** [review]

**Review by shuse2 — APPROVED** [review]
