### PR TITLE
Remove duplicate balance error - Closes #1105

### LINKED ISSUE #1105: Transaction returns incorrect error when sender does not have enough balance
### Expected behavior
Not enough balance error should reflect the original balance

### Actual behavior
Balance is shown for subtracted value.
This applies to both BaseTransaction and TransferTransaction
```
Account does not have enough LSK: 123L, balance: -0.1
```

### Steps to reproduce
1. Create a new TransferTransaction
2. input a sender who doesn't have enough balance for fee, or who does have balance for fee but not for amount
3. observe the error

### Which version(s) does this affect? (Environment, OS, etc...)
2.1-alpha.0

### PR DESCRIPTION
**Pull request by mitsuaki-u**
### What was the problem?

`verifyBalance` called in Base (for fee check) and in Transfer (and other `amount` transactions) causing duplicate insufficient balance errors.

### How did I fix it?

In Transfer, InTransfer, and OutTransfer: added extra check to make sure balance had at least enough funds for the fee, before returning balance error for `amount` to avoid duplicate errors. 

### How to test it?

npm test

### Review checklist

* The PR resolves #1105 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-transactions/src/0_transfer_transaction.ts [hunk 1]
```diff
@@ -179,9 +179,9 @@ export class TransferTransaction extends BaseTransaction {
 	protected applyAsset(store: StateStore): ReadonlyArray<TransactionError> {
 		const errors: TransactionError[] = [];
 		const sender = store.account.get(this.senderId);
-
 		const balanceError = verifyBalance(this.id, sender, this.amount);
-		if (balanceError) {
+		// Only return error if account has enough funds for fee to avoid duplicate errors
+		if (balanceError && new BigNum(sender.balance).gte(0)) {
```
Comment (shuse2) [inline packages/lisk-transactions/src/0_transfer_transaction.ts]: maybe check if the sender balance first before executing `verifyBalance`, and we could add simple function in utils/verify.ts to capture repeating `new BigNum(sender.balance).gte(0)`?
Also, this wouldn't solve the problem with the error message when sender has fee, but not amount case ='(.

**Review by shuse2 — CHANGES_REQUESTED** [review]

**Review by shuse2 — APPROVED** [review]
