### PR TITLE
Fix test for tx-pool and tx library

### LINKED ISSUE #1025: Transaction branch is failing on the build/test
### Expected behavior
All test should pass.

### Actual behavior
It fails on 
- transaction pool for the types
- transaction for verifyAndSignature test

### Steps to reproduce
npm t

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
Build and test in transaction-pool and transaction library was failing

### How did I fix it?
- Update the type for Job in transaction-pool
- make new object every time for test

### How to test it?
```
npm run build
npm run test
```

### Review checklist

* The PR resolves #1025 
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-transaction-pool/test/check_transactions.ts [hunk 1]
```diff
@@ -23,7 +23,9 @@ import transactionObjects from '../fixtures/transactions.json';
 import { wrapTransferTransaction } from './utils/add_transaction_functions';
 
 describe('checkTransactions', () => {
-	const transactions = transactionObjects.map(wrapTransferTransaction);
+	const transactions = transactionObjects
```
Comment (SargeKhan) [inline packages/lisk-transaction-pool/test/check_transactions.ts]: Rather than adding the containsUniqueData property for all transactions, we should update the TransactionObject interface in TransactionPool class to have containsUniqueData property as optional. This is because the transactions fixtures contain other types of transactions as well, the change in this PR will later create conflicts in many other PRs.

Comment (shuse2) [reply packages/lisk-transaction-pool/test/check_transactions.ts]: but is containsUniqueData optional?

**Review by SargeKhan — APPROVED** [review]

**Review by mitsuaki-u — APPROVED** [review]
