### PR TITLE
Fix multisignature double check - Closes #1122

### LINKED ISSUE #1122: Multisignature registration transaction always fails with error: 'Account is not a multisignature'
### Expected behavior
For the multisignature registration transaction, the transaction asset contains signatures property and they should be verified against the keysgroup present in the transaction asset. 
### Actual behavior
The transaction fails because BaseTransaction tries to verify signatures against the sender. Since sender is not a multisignature account, it fails with 'Account is not a multisignature account'.
### Which version(s) does this affect? (Environment, OS, etc...)
2.1.0-alpha.1

### PR DESCRIPTION
**Pull request by shuse2**
### What was the problem?
`MultisignatureTransaction` was checking the sender account for the keysgroup.

### How did I fix it?
- override processMultisignatures in `MultisignatureTransaction`
- updated test to check processMultisignatures in `MultisignatureTransaction`

### How to test it?
`npm t`

### Review checklist

* The PR resolves #1122
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

**Review by pablitovicente — APPROVED** [review]

File: packages/lisk-transactions/test/4_multisignature_transaction.ts [hunk 1]
```diff
@@ -321,18 +383,6 @@ describe('Multisignature transaction class', () => {
 			expect(errors).not.to.be.empty;
 			expect(errors[0].dataPath).to.be.equal('.signatures');
 		});
-
-		it('should return error when transaction signatures missing', async () => {
```
Comment (SargeKhan) [inline packages/lisk-transactions/test/4_multisignature_transaction.ts:325]: Why did we remove this test?

Comment (SargeKhan) [reply packages/lisk-transactions/test/4_multisignature_transaction.ts:325]: Never mind. I found the reason.

**Review by SargeKhan — APPROVED** [review]
