### PR TITLE
Receiving blocks, transactions and signatures from v1 lisk core - Closes #1081

### LINKED ISSUE #1081: Receiving blocks, transactions and signatures from v1 lisk core
### Expected behavior

P2P library should be able to receive blocks, transactions and signatures from v1 core nodes.

### Actual behavior

The node is not receiving blocks, transactions or signatures from v1 core testnet.

### Steps to reproduce

Run a sample P2P node on a remote network (since we need to handle inbound sockets).

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

Inbound messages such as blocks, transactions and signatures were not received.

### How did I fix it?

Added legacy event handlers to handle the three legacy cases.

### How to test it?

Run node on remote testnet.

### Review checklist

* The PR resolves #1081
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-p2p/src/peer.ts [hunk 1]
```diff
@@ -211,7 +237,11 @@ export class Peer extends EventEmitter {
 			isDiscoveredPeer: true,
 		};
 
-		this._peerDetailedInfo = newPeerInfo;
+		// Some fields from the main _peerInfo cannot be overridden.
+		this._peerDetailedInfo = {
```
Comment (shuse2) [inline packages/lisk-p2p/src/peer.ts:241]: maybe explicitly assigning what needs to be assign is more clear what cannot be overridden?

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: packages/lisk-p2p/src/peer.ts [hunk 2]
```diff
@@ -293,10 +323,20 @@ export class Peer extends EventEmitter {
...
 		}
-		this._outboundSocket.emit(REMOTE_EVENT_MESSAGE, {
-			event: packet.event,
-			data: packet.data,
-		});
+		// TODO later: Legacy events will no longer be required after migrating to the LIP protocol version.
+		if (
+			packet.event === 'postBlock' || 
+			packet.event === 'postTransactions' || 
+			packet.event === 'postSignatures'
```
Comment (shuse2) [inline packages/lisk-p2p/src/peer.ts]: maybe below, because lint is failing here
```
const legacyEvents = ['postBlock', 'postTransactions', 'postSignatures'];
if (legacyEvents.includes(packet.event))
```

**Review by shuse2 — CHANGES_REQUESTED** [review]

**Review by shuse2 — APPROVED** [review]
