### PR TITLE
Fix compatibility issues with Core v1.x version - Closes #1077

### LINKED ISSUE #1077: Fix compatibility issues with Core v1.x version
### Expected behavior

- The P2P library should be able to connect to the existing Lisk core testnet and communicate with the nodes as a v1 lisk-core node would.
- A socket error in the P2P library should be handled and emitted as an event so that it does not crash the P2P node.

### Actual behavior

- The P2P library has trouble connecting and interacting with the current Lisk core version. There are issues with missing fields which are causing handshake failure.
- If one of the peers causes socket failure, it crashes the P2P library.

### Steps to reproduce

Check the branch `add_p2p_sample_script`

### PR DESCRIPTION
**Pull request by jondubois**
### What was the problem?

There were some remaining issues related to incompatible fields which prevented the P2P library from connecting and interacting with lisk-core v1.x.x nodes.

### How did I fix it?

- Fixed fields to match those in the current v1 protocol exactly.
- Handled socket errors and emit them as events so that they do not crash the P2P node.
- Disable ping timeouts since they are not needed for our use case.
- Do not force the `os` field to be an alpha-only string. Often they have dots, dashes and version numbers in them which is OK.

### How to test it?

- `npm run test`
- Use the `sample/index` script in `add_p2p_sample_script` branch to test against v1 testnet.

### Review checklist

* The PR resolves #1077
* All new code is covered with unit tests
* All new code was formatted with Prettier
* Linting passes
* Tests pass
* Commit messages follow the [commit guidelines](CONTRIBUTING.md#git-commit-messages)
* Documentation has been added/updated

### CODE REVIEW

File: packages/lisk-p2p/src/validation.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ export const validatePeerInfo = (
 	const version = protocolPeer.version;
 	const wsPort = +protocolPeer.wsPort;
 	const os =
-		protocolPeer.os && isAlpha(protocolPeer.os.toString())
+		protocolPeer.os
```
Comment (shuse2) [inline packages/lisk-p2p/src/validation.ts:70]: should't we check `isAlpha` here?

File: packages/lisk-p2p/src/peer.ts [hunk 2]
```diff
@@ -83,9 +94,9 @@ export const constructPeerIdFromPeerInfo = (peerInfo: P2PPeerInfo): string =>
 const convertNodeInfoToLegacyFormat = (nodeInfo: P2PNodeInfo): ProtocolNodeInfo => (
 	{
 		...nodeInfo,
-		wsPort: nodeInfo.wsPort,
+		httpPort: nodeInfo.options ? nodeInfo.options.httpPort as number : 0,
 		broadhash: nodeInfo.options ? nodeInfo.options.broadhash as string : '',
-		nonce: nodeInfo.options ? nodeInfo.options.nonce as string : '',
+		nonce: nodeInfo.options ? nodeInfo.options.nonce as string : ''
```
Comment (shuse2) [inline packages/lisk-p2p/src/peer.ts]: let's' keep ending `,`

**Review by shuse2 — CHANGES_REQUESTED** [review]

File: packages/lisk-p2p/src/validation.ts (hunk 1 above)
Comment (jondubois) [reply packages/lisk-p2p/src/validation.ts:70]: Right now in core v1, the os string contains dots and dashes and version numbers so alpha is not suitable.

**Review by shuse2 — APPROVED** [review]
